//
//  BaseFormatter.swift
//  MyTMDB_App
//
//  Created by Codex on 2026/7/22.
//

import Foundation

// MARK: - BaseFormatter

nonisolated enum BaseFormatter {

    // MARK: - SimplifiedChineseTextMapper

    enum SimplifiedChineseTextMapper {

        static func traditionalChinese(from text: String) -> String {
            text.applyingTransform(
                StringTransform(rawValue: "Hans-Hant"),
                reverse: false
            ) ?? text
        }
    }

    // MARK: - CrewJobDisplayMapper

    enum CrewJobDisplayMapper {

        static func displayText(job: String?, department: String?) -> String? {
            jobText(job) ?? departmentText(department)
        }

        static func displayText(job: String, department: String) -> String? {
            displayText(job: Optional(job), department: Optional(department))
        }

        static func jobText(_ job: String?) -> String? {
            guard let job = normalizedDisplayText(job) else { return nil }
            return jobTranslations[normalizedKey(job)] ?? fallbackText(job)
        }

        static func departmentText(_ department: String?) -> String? {
            guard let department = normalizedDisplayText(department) else { return nil }
            return departmentTranslations[normalizedKey(department)] ?? fallbackText(department)
        }

        private static func normalizedDisplayText(_ text: String?) -> String? {
            guard let text else { return nil }

            let trimmedText = text.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmedText.isEmpty ? nil : trimmedText
        }

        private static func normalizedKey(_ text: String) -> String {
            text.lowercased()
        }

        private static func fallbackText(_ text: String) -> String {
            SimplifiedChineseTextMapper.traditionalChinese(from: text)
        }

        private static let departmentTranslations: [String: String] = [
            "acting": "演員",
            "actors": "演員",
            "art": "美術",
            "camera": "攝影",
            "costume & make-up": "服裝與化妝",
            "crew": "劇組",
            "directing": "導演",
            "editing": "剪輯",
            "lighting": "燈光",
            "production": "製作",
            "sound": "聲音",
            "visual effects": "視覺效果",
            "writing": "編劇"
        ]

        private static let jobTranslations: [String: String] = [
            "2d artist": "2D 美術",
            "2d supervisor": "2D 總監",
            "3d animator": "3D 動畫師",
            "3d artist": "3D 美術",
            "3d coordinator": "3D 協調",
            "3d director": "3D 導演",
            "3d generalist": "3D 通才",
            "3d modeller": "3D 建模師",
            "3d supervisor": "3D 總監",
            "accountant": "會計",
            "accounting supervisor": "會計主管",
            "actor": "演員",
            "acting double": "演員替身",
            "action director": "動作導演",
            "adaptation": "改編",
            "additional camera": "追加攝影機",
            "additional casting": "追加選角",
            "additional colorist": "追加調色",
            "additional construction": "追加施工",
            "additional dialogue": "追加對白",
            "additional director of photography": "追加攝影指導",
            "additional editing": "追加剪輯",
            "additional editor": "追加剪輯",
            "additional first assistant camera": "追加第一攝影助理",
            "additional gaffer": "追加燈光師",
            "additional grip": "追加攝影器材助理",
            "additional key grip": "追加器材組長",
            "additional lighting technician": "追加燈光技術員",
            "additional music": "追加音樂",
            "additional music supervisor": "追加音樂監製",
            "additional photography": "追加攝影",
            "additional post-production supervisor": "追加後期製作主管",
            "additional production assistant": "追加製作助理",
            "additional screenplay": "追加劇本",
            "additional second assistant camera": "追加第二攝影助理",
            "additional second assistant director": "追加第二副導演",
            "additional set dresser": "追加陳設師",
            "additional sound re-recording mixer": "追加重錄混音",
            "additional sound re-recordist": "追加重錄混音",
            "additional soundtrack": "追加原聲音樂",
            "additional still photographer": "追加劇照攝影",
            "additional third assistant director": "追加第三副導演",
            "additional visual effects": "追加視覺效果",
            "additional writing": "追加編劇",
            "administration": "行政",
            "adr & dubbing": "ADR 與配音",
            "adr coordinator": "ADR 協調",
            "adr editor": "ADR 剪輯",
            "adr engineer": "ADR 工程師",
            "adr mixer": "ADR 混音",
            "adr recordist": "ADR 錄音",
            "adr supervisor": "ADR 主管",
            "adr voice casting": "ADR 配音選角",
            "aerial camera": "空拍攝影",
            "aerial coordinator": "空拍協調",
            "aerial director of photography": "空拍攝影指導",
            "ager/dyer": "服裝老化與染色",
            "animal coordinator": "動物協調",
            "animal wrangler": "動物管理",
            "animation": "動畫",
            "animation coordinator": "動畫協調",
            "animation director": "動畫導演",
            "animation manager": "動畫經理",
            "animation supervisor": "動畫總監",
            "animation technical director": "動畫技術指導",
            "apprentice sound editor": "見習聲音剪輯",
            "art direction": "美術指導",
            "art direction intern": "美術指導實習生",
            "art director": "美術指導",
            "art department assistant": "美術部門助理",
            "art department coordinator": "美術部門協調",
            "art department manager": "美術部門經理",
            "art department production assistant": "美術製作助理",
            "art department trainee": "美術部門實習生",
            "art designer": "美術設計",
            "armorer": "武器管理",
            "author": "原著作者",
            "assistant accountant": "助理會計",
            "assistant art director": "助理美術指導",
            "assistant camera": "攝影助理",
            "assistant chief lighting technician": "助理燈光組長",
            "assistant costume designer": "助理服裝設計",
            "assistant dialogue editor": "助理對白剪輯",
            "assistant director": "助理導演",
            "assistant director trainee": "助理導演實習生",
            "assistant editor": "助理剪輯",
            "assistant electrician": "助理電工",
            "assistant gaffer": "助理燈光師",
            "assistant grip": "助理器材員",
            "assistant hairdresser": "助理髮型師",
            "assistant hairstylist": "助理髮型師",
            "assistant location manager": "助理場地經理",
            "assistant makeup artist": "助理化妝師",
            "assistant music supervisor": "助理音樂監製",
            "assistant picture editor": "助理畫面剪輯",
            "assistant production coordinator": "助理製作協調",
            "assistant production design": "助理製作設計",
            "assistant production manager": "助理製作經理",
            "assistant set decoration": "助理布景裝飾",
            "assistant set designer": "助理場景設計",
            "assistant sound designer": "助理聲音設計",
            "assistant sound editor": "助理聲音剪輯",
            "assistant sound engineer": "助理聲音工程師",
            "associate editor": "副剪輯",
            "associate producer": "副製作人",
            "audio post coordinator": "聲音後期協調",
            "background casting director": "背景演員選角導演",
            "background designer": "背景設計",
            "best boy electric": "燈光助理領班",
            "best boy electrician": "電工助理領班",
            "best boy grip": "器材助理領班",
            "book": "原著書籍",
            "boom operator": "收音桿操作",
            "broadcast producer": "播出製作人",
            "bts footage": "幕後花絮攝影",
            "bts photographer": "幕後花絮攝影師",
            "bts videographer": "幕後花絮錄影",
            "business affairs coordinator": "商務協調",
            "camera department manager": "攝影部門經理",
            "camera intern": "攝影實習生",
            "camera operator": "攝影機操作",
            "camera production assistant": "攝影製作助理",
            "camera supervisor": "攝影主管",
            "camera technician": "攝影技術員",
            "camera trainee": "攝影實習生",
            "cameo": "客串",
            "carpenter": "木工",
            "casting": "選角",
            "casting assistant": "選角助理",
            "casting associate": "選角副手",
            "casting consultant": "選角顧問",
            "casting coordinator": "選角協調",
            "casting director": "選角導演",
            "casting producer": "選角製作人",
            "cg animator": "CG 動畫師",
            "cg artist": "CG 美術",
            "cg supervisor": "CG 總監",
            "cgi director": "CGI 導演",
            "character designer": "角色設計",
            "character technical supervisor": "角色技術主管",
            "characters": "角色創作",
            "chief lighting technician": "燈光組長",
            "chief technician / stop-motion expert": "首席技術員 / 停格動畫專家",
            "choreographer": "編舞",
            "cinematography": "攝影",
            "clapper loader": "場記板裝片員",
            "cloth setup": "布料設定",
            "co-art director": "共同美術指導",
            "co-costume designer": "共同服裝設計",
            "co-director": "共同導演",
            "co-editor": "共同剪輯",
            "co-executive producer": "共同執行製作",
            "co-producer": "共同製作人",
            "co-writer": "共同編劇",
            "color assistant": "調色助理",
            "color grading": "調色",
            "colorist": "調色師",
            "comic book": "原著漫畫",
            "compositing artist": "合成美術",
            "compositing lead": "合成組長",
            "compositing supervisor": "合成總監",
            "concept artist": "概念美術",
            "conceptual design": "概念設計",
            "conceptual illustrator": "概念插畫",
            "conductor": "指揮",
            "consulting producer": "顧問製作人",
            "continuity": "場記連戲",
            "contract manager": "合約經理",
            "construction coordinator": "施工協調",
            "construction foreman": "施工領班",
            "construction manager": "施工經理",
            "consulting editor": "剪輯顧問",
            "coordinating producer": "統籌製作人",
            "costume design": "服裝設計",
            "costume assistant": "服裝助理",
            "costume consultant": "服裝顧問",
            "costume coordinator": "服裝協調",
            "costume designer": "服裝設計",
            "costume illustrator": "服裝插畫",
            "costume mistress": "服裝管理",
            "costume standby": "現場服裝待命",
            "costume supervisor": "服裝主管",
            "costumer": "服裝師",
            "creator": "創作者",
            "creative consultant": "創意顧問",
            "creative director": "創意總監",
            "creative producer": "創意製作人",
            "creature design": "生物設計",
            "creature technical director": "生物技術指導",
            "crowd assistant director": "群眾副導演",
            "data wrangler": "資料管理員",
            "delegated producer": "委任製作人",
            "decorator": "裝飾師",
            "development manager": "開發經理",
            "development producer": "開發製作人",
            "dialogue": "對白",
            "dialogue coach": "對白指導",
            "dialogue editor": "對白剪輯",
            "dialect coach": "方言指導",
            "digital colorist": "數位調色師",
            "digital compositor": "數位合成",
            "digital conform editor": "數位套片剪輯",
            "digital effects producer": "數位特效製作人",
            "digital effects supervisor": "數位特效總監",
            "digital imaging technician": "數位影像技術員",
            "digital intermediate": "數位中間片",
            "digital intermediate colorist": "數位中間片調色",
            "digital intermediate editor": "數位中間片剪輯",
            "digital intermediate producer": "數位中間片製作人",
            "digital producer": "數位製作人",
            "digital storyboarding": "數位分鏡",
            "director": "導演",
            "director of operations": "營運總監",
            "director of photography": "攝影指導",
            "dolly grip": "軌道車器材員",
            "dolby consultant": "杜比顧問",
            "draughtsman": "製圖員",
            "dresser": "服裝整理",
            "driver": "司機",
            "drone cinematographer": "無人機攝影",
            "drone operator": "無人機操作",
            "drone pilot": "無人機飛手",
            "editor": "剪輯",
            "editorial consultant": "剪輯顧問",
            "editorial coordinator": "剪輯協調",
            "editorial manager": "剪輯經理",
            "electrician": "電工",
            "epk camera operator": "電子新聞資料攝影",
            "epk director": "電子新聞資料導演",
            "epk editor": "電子新聞資料剪輯",
            "epk producer": "電子新聞資料製作人",
            "executive assistant": "執行助理",
            "executive co-producer": "執行共同製作人",
            "executive consultant": "執行顧問",
            "executive in charge of post production": "後期製作執行主管",
            "executive in charge of production": "製作執行主管",
            "executive producer": "執行製作",
            "executive story editor": "執行故事編輯",
            "extras casting": "臨演選角",
            "extras makeup artist": "臨演化妝師",
            "effects supervisor": "特效總監",
            "facial setup artist": "臉部設定美術",
            "field director": "外景導演",
            "fight choreographer": "動作設計",
            "finance": "財務",
            "first assistant camera": "第一攝影助理",
            "first assistant director": "第一副導演",
            "first assistant director (prep)": "第一副導演（籌備）",
            "first assistant editor": "第一助理剪輯",
            "focus puller": "跟焦員",
            "foley": "擬音",
            "foley artist": "擬音師",
            "foley editor": "擬音剪輯",
            "foley mixer": "擬音混音",
            "foley recording engineer": "擬音錄音工程師",
            "foley recordist": "擬音錄音",
            "foley supervisor": "擬音主管",
            "gaffer": "燈光師",
            "general manager": "總經理",
            "graphic designer": "平面設計",
            "graphic novel": "原著圖像小說",
            "greensman": "植物陳設",
            "grip": "攝影器材員",
            "hair assistant": "髮型助理",
            "hair department head": "髮型部門主管",
            "hair designer": "髮型設計",
            "hair supervisor": "髮型主管",
            "hairdresser": "髮型師",
            "hairstylist": "髮型師",
            "head carpenter": "木工主管",
            "head of animation": "動畫總監",
            "head of production": "製作部門主管",
            "head of story": "故事總監",
            "helicopter camera": "直升機攝影",
            "idea": "創意",
            "in memory of": "紀念",
            "insert unit director": "插入鏡頭組導演",
            "interior designer": "室內設計",
            "junior story editor": "初級故事編輯",
            "key animation": "原畫",
            "key costumer": "主要服裝師",
            "key dresser": "主要服裝整理",
            "key grip": "器材組長",
            "key hairdresser": "主要髮型師",
            "key makeup artist": "主要化妝師",
            "key hair stylist": "主要髮型師",
            "key rigging grip": "主要吊掛器材員",
            "key scenic artist": "主要景片美術",
            "key special effects": "主要特殊效果",
            "keyboard programmer": "鍵盤編程",
            "lead animator": "首席動畫師",
            "lead editor": "首席剪輯",
            "layout": "布局",
            "layout supervisor": "布局總監",
            "legal services": "法律服務",
            "lighting artist": "燈光美術",
            "lighting coordinator": "燈光協調",
            "lighting design": "燈光設計",
            "lighting director": "燈光導演",
            "lighting manager": "燈光經理",
            "lighting programmer": "燈光編程",
            "lighting supervisor": "燈光主管",
            "lighting technician": "燈光技術員",
            "line producer": "現場製片",
            "local casting": "在地選角",
            "locale casting director": "在地選角導演",
            "location assistant": "場地助理",
            "location casting": "場地選角",
            "location coordinator": "場地協調",
            "location manager": "場地經理",
            "location scout": "場地勘景",
            "location sound mixer": "現場收音混音",
            "location sound recordist": "現場錄音",
            "loop group coordinator": "群眾配音協調",
            "lyricist": "作詞",
            "main title designer": "片頭設計",
            "main title theme composer": "片頭主題曲作曲",
            "makeup & hair": "妝髮",
            "makeup & hair assistant": "妝髮助理",
            "makeup artist": "化妝師",
            "makeup department head": "化妝部門主管",
            "makeup designer": "化妝設計",
            "makeup effects": "特效化妝",
            "makeup effects designer": "特效化妝設計",
            "makeup supervisor": "化妝主管",
            "makeup trainee": "化妝實習生",
            "martial arts choreographer": "武術指導",
            "matte painter": "接景繪景",
            "mechanical designer": "機械設計",
            "modeling": "建模",
            "modelling supervisor": "建模總監",
            "motion actor": "動作捕捉演員",
            "motion capture artist": "動作捕捉美術",
            "musical": "音樂劇",
            "musical casting": "音樂選角",
            "music": "音樂",
            "music arranger": "音樂編曲",
            "music co-supervisor": "共同音樂監製",
            "music consultant": "音樂顧問",
            "music coordinator": "音樂協調",
            "music director": "音樂導演",
            "music editor": "音樂剪輯",
            "music producer": "音樂製作人",
            "music programmer": "音樂編程",
            "music score producer": "配樂製作人",
            "music supervisor": "音樂監製",
            "musician": "樂手",
            "novel": "原著小說",
            "online editor": "線上剪輯",
            "opening title sequence": "片頭序列",
            "opera": "歌劇",
            "orchestrator": "管弦編曲",
            "original casting": "原始選角",
            "original concept": "原創概念",
            "original film writer": "原創電影編劇",
            "original music composer": "原創音樂",
            "original series creator": "原創劇集創作者",
            "original story": "原創故事",
            "other": "其他",
            "painter": "油漆師",
            "payroll accountant": "薪資會計",
            "pilot": "飛行員",
            "pipeline technical director": "流程技術指導",
            "playback singer": "幕後代唱",
            "presenter": "主持人",
            "pre-visualization coordinator": "預視覺化協調",
            "pre-visualization supervisor": "預視覺化總監",
            "producer": "製作人",
            "producer's assistant": "製作人助理",
            "production accountant": "製作會計",
            "production artist": "製作美術",
            "production assistant": "製作助理",
            "production consultant": "製作顧問",
            "production coordinator": "製作協調",
            "production design": "製作設計",
            "production designer": "製作設計",
            "production director": "製作導演",
            "production executive": "製作主管",
            "production manager": "製作經理",
            "production office assistant": "製作辦公室助理",
            "production office coordinator": "製作辦公室協調",
            "production secretary": "製作秘書",
            "production supervisor": "製作主管",
            "prop designer": "道具設計",
            "prop maker": "道具製作",
            "property master": "道具主管",
            "props": "道具",
            "propmaker": "道具製作",
            "prosthetic designer": "義肢特效設計",
            "prosthetic makeup artist": "義肢特效化妝師",
            "prosthetic supervisor": "義肢特效主管",
            "prosthetics": "義肢特效",
            "public relations": "公關",
            "publicist": "宣傳",
            "pyrotechnician": "煙火技術員",
            "recording supervision": "錄音監督",
            "research assistant": "研究助理",
            "researcher": "研究員",
            "rigging gaffer": "吊掛燈光師",
            "rigging grip": "吊掛器材員",
            "rigging supervisor": "吊掛主管",
            "roto supervisor": "轉描總監",
            "rotoscoping artist": "轉描美術",
            "scenario writer": "情節編劇",
            "screenplay": "劇本",
            "screenstory": "銀幕故事",
            "scenic artist": "景片美術",
            "scoring mixer": "配樂混音",
            "script": "劇本",
            "script coordinator": "劇本協調",
            "script consultant": "劇本顧問",
            "script editor": "劇本編輯",
            "script researcher": "劇本研究",
            "script supervisor": "場記",
            "sculptor": "雕塑師",
            "second assistant camera": "第二攝影助理",
            "second assistant director": "第二副導演",
            "second second assistant director": "第二副副導演",
            "second unit director": "第二組導演",
            "second unit director of photography": "第二組攝影指導",
            "security": "保全",
            "senior animator": "資深動畫師",
            "senior colorist": "資深調色師",
            "senior executive consultant": "資深執行顧問",
            "senior story editor": "資深故事編輯",
            "senior visual effects supervisor": "資深視覺效果總監",
            "series composition": "系列構成",
            "series director": "劇集導演",
            "series writer": "系列編劇",
            "set buyer": "陳設採購",
            "set decoration": "布景裝飾",
            "set decoration buyer": "布景裝飾採購",
            "set decorating coordinator": "布景裝飾協調",
            "set costumer": "現場服裝師",
            "set designer": "場景設計",
            "set dresser": "陳設師",
            "set medic": "現場醫護",
            "set painter": "現場油漆",
            "set photographer": "現場攝影師",
            "set production assistant": "現場製作助理",
            "set propsman": "現場道具師",
            "set supervisor": "現場主管",
            "shading": "材質著色",
            "short story": "原著短篇",
            "sign painter": "招牌繪製",
            "simulation & effects artist": "模擬與特效美術",
            "software engineer": "軟體工程師",
            "songs": "歌曲",
            "sound": "聲音",
            "sound assistant": "聲音助理",
            "sound designer": "聲音設計",
            "sound director": "聲音導演",
            "sound editor": "聲音剪輯",
            "sound engineer": "聲音工程師",
            "sound effects": "音效",
            "sound effects designer": "音效設計",
            "sound effects editor": "音效剪輯",
            "sound mix technician": "混音技術員",
            "sound mixer": "混音",
            "sound post production coordinator": "聲音後期製作協調",
            "sound post supervisor": "聲音後期主管",
            "sound recordist": "錄音師",
            "sound re-recording assistant": "重錄混音助理",
            "sound re-recording mixer": "重錄混音",
            "sound supervisor": "聲音主管",
            "sound technical supervisor": "聲音技術主管",
            "special effects": "特殊效果",
            "special effects assistant": "特殊效果助理",
            "special effects coordinator": "特殊效果協調",
            "special effects makeup artist": "特殊效果化妝師",
            "special effects manager": "特殊效果經理",
            "special effects supervisor": "特殊效果總監",
            "special effects technician": "特殊效果技術員",
            "special guest": "特別客串",
            "special guest director": "特別客座導演",
            "staff writer": "編劇組成員",
            "stage director": "舞台導演",
            "stand in": "走位替身",
            "steadicam operator": "穩定器攝影師",
            "steadycam": "穩定器攝影",
            "still photographer": "劇照攝影師",
            "story": "故事",
            "story artist": "故事美術",
            "story consultant": "故事顧問",
            "story coordinator": "故事協調",
            "story developer": "故事開發",
            "story editor": "故事編輯",
            "story manager": "故事經理",
            "story supervisor": "故事總監",
            "storyboard": "分鏡",
            "storyboard artist": "分鏡美術",
            "storyboard designer": "分鏡設計",
            "street casting": "街頭選角",
            "stunt coordinator": "特技指導",
            "stunt double": "特技替身",
            "stunt driver": "特技駕駛",
            "stunts": "特技",
            "supervising adr editor": "ADR 剪輯總監",
            "supervising art director": "美術指導總監",
            "supervising dialogue editor": "對白剪輯總監",
            "supervising editor": "剪輯總監",
            "supervising film editor": "電影剪輯總監",
            "supervising music editor": "音樂剪輯總監",
            "supervising producer": "監製",
            "supervising sound editor": "聲音剪輯總監",
            "supervising sound effects editor": "音效剪輯總監",
            "tailor": "裁縫",
            "tattoo designer": "刺青設計",
            "technical advisor": "技術顧問",
            "teleplay": "電視劇本",
            "theatre play": "原著舞台劇",
            "theme song performance": "主題曲演唱",
            "thanks": "鳴謝",
            "third assistant director": "第三副導演",
            "title designer": "片名字卡設計",
            "title illustration": "片名插畫",
            "translator": "翻譯",
            "travel coordinator": "差旅協調",
            "treatment": "故事大綱",
            "unit manager": "單元經理",
            "unit medic": "單元醫護",
            "unit production manager": "單元製作經理",
            "unit publicist": "單元宣傳",
            "underwater camera": "水下攝影",
            "underwater director of photography": "水下攝影指導",
            "utility sound": "聲音支援",
            "utility stunts": "特技支援",
            "vfx artist": "視覺效果美術",
            "vfx director of photography": "視覺效果攝影指導",
            "vfx editor": "視覺效果剪輯",
            "vfx lighting artist": "視覺效果燈光美術",
            "vfx production coordinator": "視覺效果製作協調",
            "vfx supervisor": "視覺效果總監",
            "visual development": "視覺開發",
            "visual effects": "視覺效果",
            "visual effects assistant editor": "視覺效果助理剪輯",
            "visual effects compositor": "視覺效果合成",
            "visual effects coordinator": "視覺效果協調",
            "visual effects designer": "視覺效果設計",
            "visual effects director": "視覺效果導演",
            "visual effects editor": "視覺效果剪輯",
            "visual effects producer": "視覺效果製作人",
            "visual effects production assistant": "視覺效果製作助理",
            "visual effects production manager": "視覺效果製作經理",
            "visual effects supervisor": "視覺效果總監",
            "visual effects technical director": "視覺效果技術指導",
            "voice": "配音",
            "vocal coach": "聲樂指導",
            "vocals": "演唱",
            "wardrobe assistant": "服裝助理",
            "wardrobe coordinator": "服裝協調",
            "wardrobe designer": "服裝設計",
            "wardrobe master": "服裝主管",
            "wardrobe supervisor": "服裝主管",
            "weapons master": "武器主管",
            "web designer": "網頁設計",
            "wig designer": "假髮設計",
            "wigmaker": "假髮製作",
            "writer": "編劇",
            "writers' assistant": "編劇助理",
            "writers' production": "編劇製作"
        ]
    }
}
